site_name: Super Skin Pro Documentation
site_url: https://tonmaiart.github.io/superskinpro-docs/
theme:
  name: readthedocs

plugins:
  - search

nav:

    - Introduction: index.md
    - Interface Documents: skinning_tab.md
    - Release Notes : release_notes.md
    - FAQ : faq.md
    - How to Install: installation.md




markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
  - stylesheets/readthedocs-dark.css
